baseURL = 'https://teilo.xyz'
languageCode = 'en-us'
title = "teilo"

[params]
author = "Te√Ølo Millet"
description = "Meta-curious layman"

github = "teilomillet"
twitter = "teilomillet"
linkedin = "teilomillet"
email = "teilomillet@gmail.com"

[menu]
[[menu.main]]
name = "posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "about"
url = "/about/"
weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
