baseURL = 'https://teilo.xyz'
languageCode = 'en-us'
title = "teïlo"

[params]
author = "Teïlo Millet"
description = "I build open-source tools for language models and write about AI."

github = "teilomillet"
twitter = "teilomillet"
linkedin = "teilomillet"
email = "teilomillet@gmail.com"

[menu]
[[menu.main]]
name = "posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "conversations"
url = "/conversations/"
weight = 2

[[menu.main]]
name = "about"
url = "/about/"
weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
